# Generated by Django 5.2.3 on 2025-07-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
